### ISSUE TITLE
GPS

### ISSUE THREAD

**Issue by Nuwisam** [UDPSendToFailed/OTA#3]
Hello there!

First of all thank you very much for this ROM and your effort to build and maintain it - this is extremely helpful for me!

Have you had a chance to look into GPS issue? I tried to investigate it myself, but this is far beyond my skills. Maybe it would be something really easy for you to fix?

I am using this tablet as host for my DJI Mini drone and having GPS enabled would greatly benefit my user experience while flying.

Again - either way, thank you for this ROM in the first place (with or without GPS)!

**Comment by UDPSendToFailed** [comment]
Hey!

You're welcome, glad you like the ROM. :)

I have tried to fix the GPS for countless days but I haven't really had any success with it. The GPS blobs from Samsung are closed-source, and I don't really have the knowledge to adapt and build open-source ones for the tablet. No idea if they would work or not either.

I've started this as a hobby project back in 2022 april without any previous Android building or programming knowledge, and decided to share it with the community since there were no custom ROMs for this tablet (apart from some GSIs which are full of various bugs and not even 64-bit). 

Someone with the proper knowledge could fix it for sure, but just like the quad speakers (which are also broken due to closed-source blobs from Samsung), I've tried all the ideas I had for the GPS.

Also, be careful while using this ROM for things like flying drones since it has some stability issues so it might freeze or crash anytime. It's some kind of a kernel bug, probably related to zRAM (compressed swap in the RAM so the tablet can run more apps without reloading). I've tried to find a solution but no success so far.

Someday if I have time and motivation I will check the GPS again, but I don't see much hope to fix it without someone who actually knows what they are doing, and having the same tablet.

**Comment by Nuwisam** [comment]
Hi again!

If that is the case then do with this as you please - close as "Won't fix" or leave "forever" open - all of this is your free time and I really appreciate and respect that.

I have been flying for over 40 hours with this ROM and tablet and encountered totally zero issues, so no problems for me there.  I am using it only with the DJI app installed and nothing running in the background.

If the drone loses connection it returns to the take-off position by itself, so it is not that dangerous - but thanks for the heads up.

**Comment by UDPSendToFailed** [comment]
Yep, I think I will close this for now, but I'll comment if I find a solution for the GPS someday.

Hmm I see, then it could be related to the number of apps running in the background in my case. It happens rarely though, like once in a week or two.

Anyway, thanks for confirming that it works stable without background apps running.
